### ISSUE TITLE
Simplify automation

### ISSUE THREAD

**Issue by kelunik** [kelunik/acme-client#22]
The current solution is fine for using the client manually and scripting things, but it's not optimal to just automate a few domains in a few different certificates.

We already have a `acme-config.yml`. We could extend it:

``` yml
# Currently existing config variables
storage: /etc/acme
server: letsencrypt

# Important for expiry e-mails from Let's Encrypt
email: me@example.com

# Certificates to issue and renew
certificates:
 - domains: ["a.com", "www.a.com"]
   paths: ["/var/www/a.com"]

 - domains: ["b.com", "www.b.com"]
   paths: ["/var/www/b.com"]
   user: www-data
```

We could then use a command like `acme-client auto` to automatically do registration, issuance and renewal whenever invoked. Additionally, we could provide another `--config` option, so it's possible to separate configs.

We might need an additional configuration option for a script to execute after renewal happened to restart the server or so. I don't know if that should be global per config file or per certificate. I think global makes sense if we have the `--config` switch.

**Comment by kelunik** [comment]
With just some roots but many domains, the following would be easier:

```yaml
certificates:
  "/var/www/a.com":
    domains:
     - a.com
     - www.a.com

  "/var/www/a.com":
    domains:
     - a.com
     - www.a.com
    user: www-data
```

**Comment by kelunik** [comment]
``` yml
# Currently existing config variables
storage: /etc/acme
server: letsencrypt

# Important for expiry e-mails from Let's Encrypt
email: me@example.com

# Certificates to issue and renew
certificates:
 - paths:
    - /var/www/a.com: [a.com, www.a.com],
    - /var/www/img.a.com: img.a.com
   user: www-data,

 - paths:
    - /var/www/b.com: [b.com, www.b.com]
```

**Comment by FunkyM** [comment]
Great addition, played around with it but noticed one major issue.
If you have many domains (SAN) and certificates, all are requested at once which leads to a few challenge requests to become "invalid" (even despite the acme servers successfully GET's the token file). It appears there is some kind of DoS request limiting inplace per each "issue command" or rather "certificate" request. So if you fire multiple "issue" requests with like 20 domains each, some domains will always fail to validate.
The solution is to not do everything asynchronously and rather chain the calls to checkAndIssue() one after each other. This might take insignificantly longer but is certainly less "DoS-style request logic" and more reliable.

**Comment by kelunik** [comment]
Yes, already thought about that. I wanted to group those requests, so we can do it in batches, seems like I didn't do that yet.

Any other feedback to the configuration format?

**Comment by FunkyM** [comment]
The configuration format itself is fine. Just what I noticed and perhaps one idea though:
1. I don't like the current config logic. The "-c" option should be global. I am to lazy to specify/remember "--storage" and "--server" every time and rather regard these options as an "override for defaults, config file values or required options if not specified anywhere". A config file should have all needed settings and using "-c" for any command is easier (going further, just reading it from /etc/acme/acme-client.yml automatically is my current modification). Perhaps my mind just wants to solve mixing the automatic "acme-client.yml" loading with the "-c" certificate config as it's a bit awkward to distinguish both.
2. The command line "paths" map could perhaps be improved and normalized. If you have a single path and N domains, the "issue" command line "-p" argument gets N of the same paths added while one would be sufficient. Not yet a big issue unless a command line length limit is hit.
3. Perhaps the user setting could be global (have the same user for all certificates) and allow overrides individually.

My config use-case looks a bit like this now and is fine:

``` yml
...
certificates:
# firstgroup
 - paths:
    - /var/www/sharedpath:
       - example.org
       - a.example.org
       - b.example.org
   user: www-data
# secondgroup
 - paths:
    - /var/www/sharedpath:
       - example.com
       - a.example.com
       - b.example.com
   user: www-data
...
```

My final goal is to generate the config dynamically and pass it to this client.
Anyways, perhaps the config talk belongs into a different ticket. :)

**Comment by FunkyM** [comment]
I confirm this change fixes the issue for me at least:

``` patch
--- a/src/Commands/Auto.php
+++ b/src/Commands/Auto.php
@@ -82,23 +82,20 @@ class Auto implements Command {
             return;
         }

-        $promises = [];
-
         foreach ($config["certificates"] as $certificate) {
+            $promises = [];
             $promises[] = \Amp\resolve($this->checkAndIssue($certificate, $server, $storage));
-        }
+            list($errors) = (yield \Amp\any($promises));

-        list($errors) = (yield \Amp\any($promises));
-
-        if (!empty($errors)) {
-            foreach ($errors as $i => $error) {
-                $certificate = $config["certificates"][$i];
-                $this->climate->error("Issuance for the following domains failed: " . implode(", ", array_keys($this->toDomainPathMap((array) $certificate->paths))));
-                $this->climate->error("Reason: {$error}");
+            if (!empty($errors)) {
+                foreach ($errors as $i => $error) {
+                    $certificate = $config["certificates"][$i];
+                    $this->climate->error("Issuance for the following domains failed: " . implode(", ", array_keys($this->toDomainPathMap((array) $certificate["paths"]))));
+                    $this->climate->error("Reason: {$error}");
+                }
+                yield new CoroutineResult(3);
+                return;
             }
-
-            yield new CoroutineResult(3);
-            return;
         }
     }


```

**Comment by kelunik** [comment]
> I don't like the current config logic. The "-c" option should be global. I am to lazy to specify/remember "--storage" and "--server" every time and rather regard these options as an "override for defaults, config file values or required options if not specified anywhere". A config file should have all needed settings and using "-c" for any command is easier (going further, just reading it from /etc/acme/acme-client.yml automatically is my current modification). Perhaps my mind just wants to solve mixing the automatic "acme-client.yml" loading with the "-c" certificate config as it's a bit awkward to distinguish both.

They are overrides if you use the `acme-client.phar` and put an `acme-client.yml` next to it that specifies these, see https://github.com/kelunik/acme-client/blob/master/doc/installation.md#instructions.

Or are you talking about just the `auto` configuration file? It should probably use the `acme-client.yml` and then try to read a `%storage%/auto.yml`, or should I merge the two files?

**Comment by FunkyM** [comment]
If I deploy the `acme-client.phar` as `/usr/bin/acme-client`, I won't place an `acme-client.yml` plain text configuration file next to it. Configuration files in Linux usually reside in `/etc`.

Trying to read `%storage%/acme-client.yml` for defaults would probably solve that.

I can also place an `acme-client.yml` next to the phar within the source build directory, symlink it to `/usr/bin/acme-client` and specify the `--config` argument for the `auto` command but that is not something for a pure phar binary deployment scenario.

I'd probably merge the two configuration files as other commands might want to use the settings too in the future and having a single configuration file allows for using minimum arguments.

If that works, I don't see the need for a requirement of the `--storage` argument if it's already in a configuration file except if used as an override.

What worked well for me is the logic to try to read a default configuration from a list of locations, allow an optional `--config` option to specify overrides and finally override/set the final configuration from arguments. This would allow for all variants and full flexibility. My config can override everything or specific settings.

Let's look at the current cli interface:

```
# acme-client setup --storage /etc/acme --server letsencrypt:staging --email john.doe@example.org
# acme-client check --storage /etc/acme --server letsencrypt:staging --name example.org
# acme-client issue --storage /etc/acme --server letsencrypt:staging --domains example.org,a.example.org,b.example.org --path /var/www/sharedpath
# acme-client revoke --storage /etc/acme --server letsencrypt:staging --name example.org
# acme-client auto --storage /etc/acme --server letsencrypt:staging -c /etc/acme/acme-client.yml
```

If the configuration file is read (e.g. maybe even from a default path like `/etc` and/or `%storage%/acme-client.yml`) and `--storage` is not required, it could even become much simpler:

```
# acme-client setup
# acme-client check --name example.org
# acme-client issue --domains a.example.org,b.example.org --path /path/a:/path/b
# acme-client revoke --name example.org
# acme-client auto
```

All commands should still allow the options `--config`, `--storage` and `--server` to allow overriding the configuration defaults.

Finally, one could even get rid of the options argument syntax in this case to increase the usability of the cli interface (CLImate should support that afaik):

```
# acme-client setup
# acme-client check example.org
# acme-client issue a.example.org,b.example.org /path/a:/path/b
# acme-client revoke example.org
# acme-client auto
```

Looks dead simple now, doesn't it? Anyways, it's up to what you like!
I guess you have your own use-case and perhaps I am just doing too much brainstorming here and will find a way around it as long as the `auto` command issue is fixed. :)

**Comment by kelunik** [comment]
```
# acme-client setup
# acme-client check --name example.org
# acme-client issue --domains a.example.org,b.example.org --path /path/a:/path/b
# acme-client revoke --name example.org
# acme-client auto
```

That's currently possible, except that `--email` is required for `setup`, as long as you use the `acme-client.yml` next to the `acme-client.phar`. The reason it's read from the same directory is that we don't know the storage directory yet. It's uncommon to have text files in `/usr/local/bin`, but this makes the path totally configurable and doesn't block a path like `/etc/acme` that might be used by another client.

Well, usually you don't use two different clients, but that might be the case if you switched your client or are testing a new one.

> I guess you have your own use-case and perhaps I am just doing too much brainstorming here and will find a way around it as long as the auto command issue is fixed. :)

I have it in use, but just in a very small setup, no "own use-case". Please don't stop brainstorming, it really helps improving things. :-)

**Comment by FunkyM** [comment]
Sounds reasonable. I evaluated a bunch of client implementations and yours came out on top (way better than the official client and very easy to deploy using the phar on existing webservers) especially in flexibility for various use-cases. Now the `auto` command really rounds it up for automating stuff with many domains.

If you want to keep `/etc/acme` free to not block it for other acme client implementations then perhaps a better way is an application specific configuration file like `/etc/acme-client.yml`.

I think that this approach might even be the correct solution as on Windows simple configuration files are usually next to the binary `./acme-client.yml` compared to Linux which uses `/etc/acme-client.yml` (system-wide) and `$HOME/.acme-client.conf` (user-local). That also does not imply knowing about the storage directory (even if it is `./data` by default afair).

How about trying to read a `./acme-client.yml` first then on Linux try `/etc/acme-client.yml`?
This would also help when packaging your great app for a distribution as the config should end up in `/etc` anyways otherwise review will fail with a configuration file in a `bin` directory.

What do you think about the `auto --config` option? Merge to read `certificates` from the main configuration file or keep configuration files separate?
Perhaps just removing the limitation of `"Provided YAML file had unknown options: ..."` would be sufficient as the `auto --config` option could then simply reuse the same YAML file.

**Comment by kelunik** [comment]
**Currently implemented format**

``` yml
# Already existing config variables
storage: /etc/acme
server: letsencrypt

# Important for expiry e-mails from Let's Encrypt
email: me@example.com

# Certificates to issue and renew
certificates:
 - user: www-data
   bits: 4096
   paths:
     /var/www/a.com: [a.com, www.a.com],
     /var/www/img.a.com: img.a.com
 - paths:
    - /var/www/b.com: [b.com, www.b.com]
```

I also added the proposed config file locations. Could you test it and give further feedback?
