### ISSUE TITLE
Auto not able to generate a cert with and without www.

### ISSUE THREAD

**Issue by Lodesys** [kelunik/acme-client#31]
I also like the new auto option, but having problems generating certificates where multiple domains map to the same directory.

As a simple example, if I want a certificate for both www.example.org and example.org, I would include this in acme-client.yml config file:

```
certificates:
    - paths:
        /www/example: www.example.org
        /www/example: example.org
```

I do get a single SSL certificate, but only the first domain – www.example.org – is included as both names are using the same directory.

One way around this would be to swap the path and domain, as the domain is always going to be unique within a single certificate.

```
certificates:
    - paths:
        www.example.org: /www/example
        example.org: /www/example
```

Any suggestions?

**Comment by kelunik** [comment]
The reason it's that way is that you may want to use one path for multiple domains. You can just use an array there:

``` yml
certificates:
 - paths:
     /var/example:
      - example.org
      - www.example.org
```

Maybe we could also allow both directions, since we always know whether it's an absolute path or host name.
