### ISSUE TITLE
Error in config file on Windows?

### ISSUE THREAD

**Issue by abrguyt** [kelunik/acme-client#51]
I've got the client up and running on Windows, I've managed to register as a new user, and have set up a acme-client.yml global config file. All good so far.

Manually I can successfully obtain new certificates with the command:

acme-client.phar issue -d my.domain.com -p "D:/data/web/website"

However when I use 'acme-client auto' and try to use the certificates config from the .yml file I get an error: "Notice: undefined index: paths in ....... /Auto.php on line 178"

So apparently it can't read the certificates config in the .yml file properly, but what am I doing wrong in the following config section for that (after the storage, server and email section):

certificates:
    paths:
        "D:/data/web/website":
            - my.domain.com

Any ideas greatly appreciated :-)

**Comment by kelunik** [comment]
Did you indent the `paths` segment?

```yml
certificates:
  paths:
    "D:/data/web/website":
      - my.domain.com
```

**Comment by abrguyt** [comment]
Yes, exactly like that (initially indentation got lost by Github) - I also tried adding the single domain straight after the path, with the same result.

I can't figure out how to do indentation here in Github :-)

**Comment by kelunik** [comment]
Ah, you probably missed a dash like that:

```yml
certificates:
 - paths:
    "D:/data/web/website":
      - my.domain.com
```
